### ISSUE TITLE
gradle 错误

### ISSUE THREAD

**Issue by includeleec** [dolphineor/modern-java-web-scaffold#1]
FAILURE: Build failed with an exception.

* What went wrong:
Task 'fatCapsule' not found in root project 'modern-java-web-scaffold'.

**Comment by includeleec** [comment]
download project , excute 'gradle :backend:clean fatCapsule'

**Comment by conchz** [comment]
@includeleec Sorry for inconvenience, fatCapsule is deprecated, but forgot updating document, now using docker is a better choice. You can have a try, thanks for issue.

**Comment by includeleec** [comment]
i use windows , when i run '.\deploy-backend',the terminal will open a dialog which to select one type to excute.
how to do?? thx.
